### ISSUE TITLE
How to ?

### ISSUE THREAD

**Issue by Cyb3rG0D7** [TH3-MA3STRO/messenger-spammer#1]
How you can send a specific message only once
To all my Facebook friends?
For example, I can get an id list in a .txt file and have the program send the specified message to all the id of that list only once per person, or you can put the number of times, for one time you could put 0 or 1

**Comment by TH3-MA3STRO** [comment]
Do you want me to add that as a feature?
But it's very easy, if you want to do it on your own

**Comment by Cyb3rG0D7** [comment]
I still do not know how to program, I have just been watching python
so please ask.

**Comment by TH3-MA3STRO** [comment]
I'll try to add it as soon as possible :D
Thank You for checking out this repo :)

**Comment by Cyb3rG0D7** [comment]
pip3 install -r requirements.txt 
Requirement already satisfied: selenium in /usr/local/lib/python3.7/dist-packages (from -r requirements.txt (line 1)) (3.141.0)
Collecting pyinquirer (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/fb/4c/434b7c454010a284b49d6f1d446fe8dc5960415613d8c0225b9e2efb6724/PyInquirer-1.0.3.tar.gz
Collecting promt_toolkit==1.0.14 (from -r requirements.txt (line 3))
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/simple/promt-toolkit/

**Comment by TH3-MA3STRO** [comment]
Oof :100: 
Sorry for the inconvenience :(
I've edited the file now :)
Please clone this repo again and try :D

**Comment by Cyb3rG0D7** [comment]
Thanks, everything is already correctly
I will be waiting for the update with the new features.
I know if I can create an interface like the bots of this tool
https://github.com/xHak9x/fbi

**Comment by TH3-MA3STRO** [comment]
Added the feature you were asking for dude! :)
Check it out and give reviews and suggestions :D

**Comment by Cyb3rG0D7** [comment]
In this part as I tell you where is the .txt with the id of the people?
Wouldn't it be better for the program itself to do the .txt?
Enter spam details!
? Please specify a type of ticket! Enter multiple usernames through a file

**Comment by Cyb3rG0D7** [comment]
I am using fbi to get the id in a .txt
it would be good to have the dump_id option of fbi to remove the .txt and save them in an "output" folder and if it is included or customized, the program says the available lists and select which one
Enter spam details!
? Please specify an input type! Enter multiple usernames through a file
? Enter the filename containing the usernames: lista_id.txt
? Enter the message you wish to spam: https://www.youtube.com/watch?v=xYwHdVLh71U
? Enter the count of messages: 1
Traceback (most recent call last):
  File "run.py", line 29, in <module>
    driver = webdriver.Chrome ('chromedriver', options = options)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities = desired_capabilities)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session (capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute (Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response (response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class (message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location / usr / bin / chromium is no longer running, so ChromeDriver is assuming that Chrome has crashed.)

**Comment by Cyb3rG0D7** [comment]
![image](https://user-images.githubusercontent.com/35184132/71922876-d0041400-3159-11ea-9f0b-d57c785888c3.png)
I know if I'm telling you the route well

**Comment by TH3-MA3STRO** [comment]
Did you add chromedriver to the path variable?
And can you please add a screenshot of your txt file?
Also, I'll definitely work on that "select file" feature :)

**Comment by Cyb3rG0D7** [comment]
I have not created any txt .. I would like to capture the id of my friends and save the id in a txt .. not the usernames

**Comment by Cyb3rG0D7** [comment]
you can review this project too
https://github.com/pedromgdo/Spammy-the-bot

**Comment by Cyb3rG0D7** [comment]
to create the ID list
i use fbi
the get_info option
then dump_id
and create me the .txt with the id of all my friends
https://github.com/xHak9x/fbi
